### PR TITLE
added auto commenting feat for PR Merged

### LINKED ISSUE #100: Feat: Auto Commenting feature for PR Merged
### Describe the feature

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

### Add ScreenShots

PR merged

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #100 

@PatilHarshh please review my PR and merge it if it is good to go

### CODE REVIEW

**Comment by PatilHarshh** [comment]
Great !!

**Comment by Asymtode712** [comment]
@PatilHarshh Can you please label this PR with 'gssoc' and 'level1' labels

**Comment by Asymtode712** [comment]
@PatilHarshh Can you please label this PR with 'gssoc' and 'level1' labels as it is mandatory for both issues as well as PRs to be labelled

labels

**Comment by PatilHarshh** [comment]
this pr is not working

**Comment by PatilHarshh** [comment]
Screenshot (260)

**Comment by Asymtode712** [comment]
@PatilHarshh just a min I will fix it

**Pull request merged**
