### PR TITLE
Feat : Added Resume Builder

### PR DESCRIPTION
**Pull request by mukilan2815**
## Related Issue
Completed the Resume builder

## Description
Added Resume builder where user can edit the resume by clicking on the informations .

## Type of PR

- [ ] Bug fix
- [ x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x ] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [x ] I have tested the changes thoroughly before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.

##Resolves:
#215

### CODE REVIEW

**Comment by mukilan2815** [comment]
@somilyadav7 Please review it and close this PR

**Comment by somilyadav7** [comment]
tag the owner

**Comment by mukilan2815** [comment]
@PatilHarshh

**Comment by PatilHarshh** [comment]
just make it standardize , remove names and all @mukilan2815

**Comment by mukilan2815** [comment]
Can u close this pr? I will make changes in another pr for sure... Please close in gssoc'24 level 3.
And say me the sample names and details to out it that resume? Or I will make it as random name and details?

**Comment by mukilan2815** [comment]
@PatilHarshh Please check it now and merge it bro

**Comment by PatilHarshh** [comment]
conflicts !!

**Comment by mukilan2815** [comment]
@PatilHarshh Check now bro

**Comment by PatilHarshh** [comment]
you should give little instruction or the guide how to edit the resume on that page ! explore little more and make changes

**Comment by mukilan2815** [comment]
done

**Comment by mukilan2815** [comment]
@PatilHarshh Have you checked it ??

**Comment by PatilHarshh** [comment]
Good ! @mukilan2815 Just one more Bug  do check in dark mode once adjust it and will merge your pr then

**Comment by mukilan2815** [comment]
@PatilHarshh Please assign level 3 label for this coz i have created a new page and lots of work. 
Completed now check it

**Comment by PatilHarshh** [comment]
I Really appreciate Your work brother ! We would need of such creative minds but i do feel level2 will be best for this pr as i reviewd your code

**Pull request merged**
