### PR TITLE
Added contact form

### PR DESCRIPTION
**Pull request by ayush-848**
## Related Issue
#180 

## Description
Added contact form in homepage above footer

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by ayush-848** [comment]
@PatilHarshh It is my humble request to label it as level2 because beside adding the form, I have also made the footer links responsive.
If you are satisfied with the changes I'd like you to do so.
Thank you

**Comment by PatilHarshh** [comment]
Screenshot (262)

**Comment by PatilHarshh** [comment]
Not Good Responsive !! From Top make more appealing

**Comment by ayush-848** [comment]
@PatilHarshh done
image

**Comment by ayush-848** [comment]
@PatilHarshh please check it now

**Comment by ayush-848** [comment]
@PatilHarshh Please check the PR now
I have made it appealing and responsive

**Comment by PatilHarshh** [comment]
its too simple , Can you make more Appealing

**Comment by ayush-848** [comment]
> its too simple , Can you make more Appealing

I can
I made that coz it matches the website theme

**Comment by ayush-848** [comment]
https://github.com/PatilHarshh/Kaam-Do/assets/126975547/c8797332-dec7-4905-9d41-abf594ba2001



@PatilHarshh see the new changes. It took a lot of efforts. I hope you like it

**Comment by ayush-848** [comment]
> Untitled.video.-.Made.with.Clipchamp.3.mp4 
> @PatilHarshh see the new changes. It took a lot of efforts. I hope you like it

If you like it, merge it, assign the PR and add the labels

**Comment by PatilHarshh** [comment]
Please remove the contact page from home page .

**Comment by ayush-848** [comment]
> Please remove the contact page from home page .

@PatilHarshh done

**Comment by ayush-848** [comment]
@PatilHarshh I have removed it from home page as you said. Please check

**Comment by PatilHarshh** [comment]
Screenshot (272)

**Comment by ayush-848** [comment]
@PatilHarshh done

**Comment by PatilHarshh** [comment]
can you do orangish color ?

**Comment by ayush-848** [comment]
> can you do orangish color ?

done

**Comment by ayush-848** [comment]
@PatilHarshh I did everything as you said. I am expecting a level 3 from you. I hope you will appreciate all of my efforts

**Comment by ayush-848** [comment]
@PatilHarshh  I did everything as you said. I am expecting a level 3 from you. I hope you will appreciate all of my efforts by doing so.

**Comment by PatilHarshh** [comment]
There is no intergration of backend ! We should move for leve 2!

**Pull request merged**
