### PR TITLE
resume enhance completed

### PR DESCRIPTION
**Pull request by Varsani2520**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
enhance the resume design
## Description
[Please include a brief description of the changes or features added]
user able to edit and download the resume 
## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [x] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Varsani2520** [comment]
@PatilHarshh ,please merged it and also add the label GSSOC as well as level 1,2 or 3

**Comment by Varsani2520** [comment]
@PatilHarshh , please merged it

**Comment by PatilHarshh** [comment]
Add a box or div below or above the resume instructing about how to use the resume or how to edit resume! @Varsani2520

**Review by Varsani2520 — COMMENTED** [review]
edit done

**Comment by Varsani2520** [comment]
@PatilHarshh ,i solve the edit issue

**Comment by PatilHarshh** [comment]
> Add a box or div below or above the resume instructing about how to use the resume or how to edit resume! @Varsani2520

please read carefully and make changes accordingly... if any problem ask me

**Comment by Varsani2520** [comment]
@PatilHarshh ,i added instruction how to use and edit ...
image

**Comment by Varsani2520** [comment]
@PatilHarshh ,please merged it

**Comment by Varsani2520** [comment]
@PatilHarshh ,merged it

**Comment by PatilHarshh** [comment]
can you make seperate box for instruction ! and just make preetify

**Comment by Varsani2520** [comment]
@PatilHarshh 

image

as you mention, i update code and make separate border box for instructions

**Comment by PatilHarshh** [comment]
check in dark mode @Varsani2520

**Comment by Varsani2520** [comment]
@PatilHarshh ,now check it

**Comment by Varsani2520** [comment]
@PatilHarshh ,i solved the issue, now you merged it

**Comment by Varsani2520** [comment]
If you this pr merged it then i able to solve another issue in your repo

**Pull request merged**
