### PR TITLE
added auto commenting feat for PR Raised

### LINKED ISSUE #99: Feat: Auto Commenting feature for PR Raised
### Describe the feature

This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Add ScreenShots

PR raised

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #99 

@PatilHarshh please review my PR and merge it if it is good to go

### CODE REVIEW

**Comment by Asymtode712** [comment]
@PatilHarshh Can you please label this PR with 'gssoc' and 'level1' labels

**Comment by PatilHarshh** [comment]
already mentioned in issue !

**Comment by Asymtode712** [comment]
@PatilHarshh Can you please label this PR with 'gssoc' and 'level1' labels as it is mandatory for both issues as well as PRs to be labelled

labels

**Comment by Asymtode712** [comment]
@PatilHarshh   please add 'gssoc' and 'level1' labels

Thank you!

**Pull request merged**
