### PR TITLE
adding userAuth routes using jwt

### PR DESCRIPTION
**Pull request by ANSH127**
adding user-authentication routes in server generating token using jwt
solving issue #4

### CODE REVIEW

**Comment by PatilHarshh** [comment]
@ANSH127  Have Raise issue for it ? or Have You mentioned Description for it ? To Make Contribution in better Way You must follow the Steps !

**Comment by ANSH127** [comment]
> @ANSH127 Have Raise issue for it ? or Have You mentioned Description for it ? To Make Contribution in better Way You must follow the Steps !
i have mentioned issue and description..

**Comment by PatilHarshh** [comment]
You Should Mention The Details in PR too ! it will easy for Maintainers and mentors too

**Comment by ANSH127** [comment]
> You Should Mention The Details in PR too ! it will easy for Maintainers and mentors too

okay next time onwards I'll take care

**Comment by ANSH127** [comment]
may you accept this request or make another branch for that issue than pull?

**Comment by PatilHarshh** [comment]
As of Now it is assigned. it is assigned who raised this issue first 🚀

Closing this PR !!

Thankyou 
Looking forward for Contribution 🚀

**Pull request closed without merging**
