### PR TITLE
Home and about UI

### PR DESCRIPTION
**Pull request by Varsani2520**
Hi @PatilHarshh ,
Home is:
image

about is:
image

### CODE REVIEW

**Comment by Varsani2520** [comment]
Hi @PatilHarshh ,
if any changes do you want then inform me

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,check the PR #93  and merged it

**Comment by PatilHarshh** [comment]
There is any error ? because preview is not visible !

**Comment by PatilHarshh** [comment]
https://kaam-do-git-fork-varsani2520-home-847499-patilharshhs-projects.vercel.app/?_vercel_share=gsA89JxyDcdsvS7TaGAyrihlML589YdR

**Comment by PatilHarshh** [comment]
This PR's code have some issue not rendering any thing !!

**Comment by Varsani2520** [comment]
@PatilHarshh ,
can you send me vercel Deploy error message ,
because in my localhost work correctly

**Comment by PatilHarshh** [comment]
There is no error but not rendereing anything !! I am merging this if it will not work then i have to revert this issue !! Let me give confirmation from your side !! @Varsani2520

**Comment by Varsani2520** [comment]
ok,i ll try

**Comment by PatilHarshh** [comment]
for further queries ping me on discord @Varsani2520

**Comment by Varsani2520** [comment]
ok

**Pull request closed without merging**
