### PR TITLE
user search category then display that category

### PR DESCRIPTION
**Pull request by Varsani2520**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
 Feat:add search option for search the job #199 
## Description
[Please include a brief description of the changes or features added]
user search category then display that category card
## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,check it and merged it also add the label Gssoc and level2

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,please merge it

**Comment by PatilHarshh** [comment]
Hello @Varsani2520  Are you intersted to Regulate this Repository ?

**Comment by Varsani2520** [comment]
@PatilHarshh ,yes i am interested this regulate  repository

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,merged it and also add label as per issue no 199

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,give the response

**Comment by Varsani2520** [comment]
otherwise i dont like to contribute with you

**Comment by Varsani2520** [comment]
@PatilHarshh ,since 5 days you still not merge my PR
if you not going to response me within day i will complain your repo in gssoc flag

**Pull request merged**
