### PR TITLE
footer

### PR DESCRIPTION
**Pull request by siddhant-2002**
footer color changed

copyright updated

margin n padding changed

### CODE REVIEW

**Comment by siddhant-2002** [comment]
image

**Comment by PatilHarshh** [comment]
what changes you did ! just color changing ? which do not suites the site ?

**Comment by siddhant-2002** [comment]
image

your footer is looking like this previously 

I have changed the whole padding put all content at the center and flex is wrapped when we shrink for responsive all content is getting one after another column wise 

like this 
image

and colour I have used is complimentary color to your color its usually used with the yellow color it looks good ig if you will see carefully with whole website 

image

**Comment by siddhant-2002** [comment]
any updates ? whats your openion @PatilHarshh

**Comment by PatilHarshh** [comment]
no ! really like existing one ! do feels existing one is good ! any other changes you want to perform there ?

**Comment by siddhant-2002** [comment]
last footer line copyright thing i think that would be ok at the center and 2024 copyright added 

and responsiveness of footer also done if you think it is ok you should merge my pr I will change color again and do next request

**Comment by siddhant-2002** [comment]
image


image

**Pull request merged**
