### PR TITLE
successfuly fetching blogs from Medium  Api

### PR DESCRIPTION
**Pull request by AnanyaJain25**
https://github.com/PatilHarshh/Kaam-Do/assets/136808696/e00b8e74-be7d-4b6a-a972-3fc5b6d4e978

Working fine and fetching latest blogs related to jobs

##Fixes
Feat:Integrating Medium(Blogging Website) API #165

### CODE REVIEW

**Comment by PatilHarshh** [comment]
Screenshot (265)

**Comment by PatilHarshh** [comment]
Solve the Deployement Errors

**Comment by AnanyaJain25** [comment]
> Solve the Deployement Errors

did you do npm install react-slick?
if not then first run:
npm install react-slick
then try builiding again:
npm run build

**Comment by AnanyaJain25** [comment]
hey @PatilHarshh is it working?

**Comment by PatilHarshh** [comment]
can it can be done by you? @AnanyaJain25

**Comment by AnanyaJain25** [comment]
> can it can be done by you? @AnanyaJain25

It is not opening from my account

**Comment by AnanyaJain25** [comment]
> can it can be done by you? @AnanyaJain25

what should i do please instruct

**Comment by AnanyaJain25** [comment]
please try now

**Comment by PatilHarshh** [comment]
have you changed ? @AnanyaJain25

**Comment by AnanyaJain25** [comment]
> have you changed ? @AnanyaJain25

can we connect on discord?

**Comment by PatilHarshh** [comment]
discord handle : rabbit9891

**Comment by AnanyaJain25** [comment]
> discord handle : rabbit9891

sent

**Comment by AnanyaJain25** [comment]
> > discord handle : rabbit9891
> 
> sent

**Comment by AnanyaJain25** [comment]
> have you changed ? @AnanyaJain25

I have actually made some changes so you can try once.

**Review by PatilHarshh — APPROVED** [review]
approved

**Comment by PatilHarshh** [comment]
Cool !! @AnanyaJain25

**Review by PatilHarshh — COMMENTED** [review]
reviewed

**Pull request merged**
