### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by VShalini01**
I have made the following enhancements:
Added a feature (Efficient Search)
Added information about the Tech-Stack used for the project 
Elaborated the Installation Steps.
Provided access to the MIT License

Thank You for assigning the issue!

### CODE REVIEW

**Comment by PatilHarshh** [comment]
mention Issue number you are resolving

**Comment by VShalini01** [comment]
@PatilHarshh Issue no. 26

**Comment by PatilHarshh** [comment]
Good Job @VShalini01 ! Looking Forward for more contribution

**Comment by VShalini01** [comment]
@PatilHarshh Can you please assign GSSoC label to the PR

**Comment by PatilHarshh** [comment]
Done !

**Pull request merged**
