### PR TITLE
Detail page display

### PR DESCRIPTION
**Pull request by Varsani2520**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
#157 
## Description
[Please include a brief description of the changes or features added]
user click on any job then display specifically that related job information display with description
## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
before:
image
user click on any card or job then display this image:
image
also user click on this :
image
then display that related detailed page:
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,i solved the issue with my expertise ,
now you add the label and merge it.
also do you have any requirement then inform me

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,merge it

**Comment by Varsani2520** [comment]
if you help me then i also help in your website

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,merge it and check it

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,
check it and merge it ,
if you want to aadditional content then inform me i will do it

**Comment by Varsani2520** [comment]
@PatilHarshh 

i detailed page for all job cards as you say
it's your responsibility to check it and merge it

you are not giving response within this  day, i will complain you in gssoc community

**Comment by PatilHarshh** [comment]
Hey @Varsani2520 !! I was busy in my Examination. I am taking too long because i am reviewing the Quality code. As you see in the issue section there is almost 105 issues . Most of them are spam ! reviewing each and every issue and assigning genuine one . and reviewing Before merging takes Little Time.
 Once again Sorry For Delay !! 
Don't worry I will merge it soon after Reviewing

**Comment by Varsani2520** [comment]
ok @PatilHarshh ,take your time ,if you nees any help then inform me ,i'll help you

**Comment by PatilHarshh** [comment]
https://kaam-do-git-fork-varsani2520-detai-0bf082-patilharshhs-projects.vercel.app/?_vercel_share=dc7VVrSs5XS6FKF9xGlhFdrZdylmDddD

**Comment by PatilHarshh** [comment]
@Varsani2520 Check Once Deployment

**Comment by Varsani2520** [comment]
ok @PatilHarshh ,i'll check

**Pull request closed without merging**
