### PR TITLE
Contact page

### LINKED ISSUE #73: BUG:contact us missing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@PatilHarshh ,
i think you forgot the contact page ,its a important part of e-commerce website
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Varsani2520**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
contact is not created
close #73 

## Description
[Please include a brief description of the changes or features added]
i created a contact route as well as user click on contact then go to /contact-us page ...
## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]
i created a contact route as well as user click on contact then go to /contact-us page ...

### CODE REVIEW

**Comment by PatilHarshh** [comment]
I am not checking code make sure it is  correct !! @Varsani2520

**Comment by Varsani2520** [comment]
@PatilHarshh ,I solved the conflicts ,
can you tell me what exactly issue like in localhost or live web not display my code 
in localhost work perfectly,
if in live issue then i have 1 solution

**Comment by PatilHarshh** [comment]
Ok Great !! @Varsani2520  Let me merge !!

**Comment by PatilHarshh** [comment]
Reverting Changes !! its problematic

**Comment by Varsani2520** [comment]
@PatilHarshh 

what kind of problem it create? 
can you provide me screen short

**Comment by PatilHarshh** [comment]
some thing error while deployment ! directly shows 404 ! i need to go through your code first till then please wait !

**Pull request merged**
