### PR TITLE
Faqs

### LINKED ISSUE #78: BUG: FAQ page is missing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@PatilHarshh 

There is no FAQ page 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

BUG: FAQ page is missing #78
close #78

@PatilHarshh 

Please check this and merge it
i completed FAQ's Page and added link in footer 

when user click `FAQ` from footer they will redirect to `/FAQ` page

it will look like this
- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhruv8433** [comment]
@PatilHarshh 

previously i made pr #86 

but due to more than one pr the footer link was not added in commit 
so i created seperate pr for that

kindly please check this and merge it

**Comment by dhruv8433** [comment]
@PatilHarshh 

please response
as a mentor it's your responsibiliy to give answer 

if you want any modifications, than please inform me

i created faqs page please check that and merge it

**Comment by dhruv8433** [comment]
@PatilHarshh 

as a mentor 
please response

if you not give response within this day
i will complain your project in gssoc community flag 🚩

**Comment by PatilHarshh** [comment]
@dhruv8433  LGTM!

**Comment by dhruv8433** [comment]
@PatilHarshh 

Can you please tell me why you assign level 1!!!

**Pull request merged**
