### PR TITLE
sticky navbar

### PR DESCRIPTION
**Pull request by prachita0504**
## Related Issue
issue number: #154 

## Description
I make the navbar sticky.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by PatilHarshh** [comment]
Nice ! @prachita0504

**Comment by PatilHarshh** [comment]
Can you able to add animation to nav bar ! so that it disapper after passing the banner!

**Comment by prachita0504** [comment]
What exactly you want

**Comment by PatilHarshh** [comment]
Navbar should Be Sticky till the Half Only ! Understood ?

**Comment by prachita0504** [comment]
i think navbar is something that will sticky for whole the website

**Pull request merged**
