### PR TITLE
Made some changes in footer section to make it look good

### PR DESCRIPTION
**Pull request by somilyadav7**
Issue : #54 
Kept the footer section small and simple. Email now entered is now visible. Improved the spacing and alignmnet.

### CODE REVIEW

**Comment by PatilHarshh** [comment]
mention issue here

**Comment by somilyadav7** [comment]
> mention issue here

Metioned Bro

**Comment by PatilHarshh** [comment]
Resolve Conflicts !!

**Comment by PatilHarshh** [comment]
Great !

**Comment by somilyadav7** [comment]
@PatilHarshh Bro you didn't add GSSOC label to it thats why its not showning in my leaderboard

**Pull request merged**
