### PR TITLE
Filter jobs

### LINKED ISSUE #72: BUG: Filter Not Working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Filter jobs not working
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
@PatilHarshh 

## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

BUG: Filter Not Working #72

close #72

## Description
[Please include a brief description of the changes or features added]
- added filter that find job's based on user preferences
- update jobs data (json file)
- added multiple types of jobs with experience 

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

job type = contract
image

job type = part-time
image

job with experience of 2-6 years
image

jobs with experience of 1 years or 2 - 6 years with full time
image

also added search query 
we try to search `system Analyst` with some filter
image

search jobs by their locations
here we try to find jobs of location `West US`
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

Please check this and merge it

### CODE REVIEW

**Comment by dhruv8433** [comment]
@PatilHarshh 
- i added filter by `job type` and `experience` as well `search with job title` and `location` please check this out and merge it

**Comment by dhruv8433** [comment]
@PatilHarshh 

as a mentor, please response
i already create 4 5 pr and you don't even merge single
it's your responsibility to answer and give response

**Comment by PatilHarshh** [comment]
> @PatilHarshh
> 
> as a mentor, please response i already create 4 5 pr and you don't even merge single it's your responsibility to answer and give response

Sorry ! @dhruv8433  Being Late Response ! Your Deployment giving errors , make sure your update your local repository and then push code

**Comment by dhruv8433** [comment]
@PatilHarshh 

check this out 
image
there is no build error in my code

the error is already present in current build 
image

**Comment by dhruv8433** [comment]
@PatilHarshh the current build have erros that's why i got errors to in my deployment

**Comment by PatilHarshh** [comment]
did You updated your local repo ? command ::  " npm pull "

**Comment by dhruv8433** [comment]
@PatilHarshh 

already up-to-date
image

**Comment by dhruv8433** [comment]
@PatilHarshh now you can merge this 

and also ensure there is no signle error as well conflict
image

**Comment by dhruv8433** [comment]
@PatilHarshh Please check this and response

**Comment by dhruv8433** [comment]
@PatilHarshh Response !!!

**Comment by dhruv8433** [comment]
@PatilHarshh ,
when userr click on find-job tab then display this page ,
user can able to filter job with location,job type and based on experiance:
this is navigation:
image

and this is /find-job route then display :
image

**Comment by PatilHarshh** [comment]
Great !! @dhruv8433

**Comment by dhruv8433** [comment]
@PatilHarshh 

also note that i already completed
#86 and #75

so please close this and this #118 i provided all functions of search and filter than why you added level 1...!!

**Pull request merged**
