### PR TITLE
home and about ui

### PR DESCRIPTION
**Pull request by Varsani2520**
pr #93

@PatilHarshh 

## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
- i completed home page ui as well about page ui

## Description
[Please include a brief description of the changes or features added]
- created 2 seperate route for home and about `/about` and `/`  

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

when i try to attempt deploy your main branch which i re-clone again then also i got 404 
but my home and about page are working properly in localhost as well vite preview 
i have no access to deploy your web in my vercel account 

check this
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by PatilHarshh** [comment]
yeah !! now looking Good ! @Varsani2520  . i want certain changes  in UI Can you implement now or in another issue ?

**Comment by Varsani2520** [comment]
@PatilHarshh ,
sure i would like to work on that ui improvement
can you please merge this 
and let me know what kind of ui improvement you need

**Comment by PatilHarshh** [comment]
mention issue no. @Varsani2520

**Comment by PatilHarshh** [comment]
> @PatilHarshh , sure i would like to work on that ui improvement can you please merge this and let me know what kind of ui improvement you need

where should we talk ?

**Comment by Varsani2520** [comment]
@PatilHarshh ,
What ui changes do you want ? if you have any kind of particular ui than please provide me and i can implement in code

**Comment by Varsani2520** [comment]
@PatilHarshh 

if you merge my pull request than why i don't see my name in contributation list 
if i can't see my name than how i will contribute in another issue
i can only redesign your ui if i can see my name in that list

check this image
image

**Comment by PatilHarshh** [comment]
> @PatilHarshh
> 
> if you merge my pull request than why i don't see my name in contributation list if i can't see my name than how i will contribute in another issue i can only redesign your ui if i can see my name in that list
> 
> check this image image

As i said did you mention issue number here which it closes ?

**Comment by Varsani2520** [comment]
@PatilHarshh ,

as a contributor, my question is why my name is not display in your repositories as a contributor list

**Pull request merged**
