### PR TITLE
Added 404 page

### PR DESCRIPTION
**Pull request by Jagpreet153**
## Related Issue
#254 

## Description
I have added animation in 404 page 

## Type of PR
- [x] Feature enhancement

## Screenshots / videos (if applicable)
Screenshot 2024-06-18 151755

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Kindly add relevant labels to this PR

### CODE REVIEW

**Comment by PatilHarshh** [comment]
conflicts

**Comment by Jagpreet153** [comment]
> conflicts

Resolved conflicts

**Comment by PatilHarshh** [comment]
Screenshot (280)

**Comment by Jagpreet153** [comment]
@PatilHarshh Kindly review it now

**Pull request merged**
