### PR TITLE
footer redesign

### PR DESCRIPTION
**Pull request by Varsani2520**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
#198 
## Description
[Please include a brief description of the changes or features added]
i enhance the footer where added content as well as design the footer 
## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,
check it and merged it as well as add label as per #198 
closed #198

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,please check it and merged it

**Comment by Varsani2520** [comment]
hey @PatilHarshh ,give response me

**Comment by PatilHarshh** [comment]
remove that Dumy text!

**Comment by Varsani2520** [comment]
> remove that Dumy text!

i dont understood i redesign the footer for theme matching website :image tell me what you want to remove

**Comment by Varsani2520** [comment]
@PatilHarshh ,now check it ,i remove dummy text

**Comment by Varsani2520** [comment]
@PatilHarshh ,please check it and merge it ,i completely footer dynamically ,
now it work completely

**Comment by Varsani2520** [comment]
@PatilHarshh ,please check it and merge it ,i completely footer dynamically ,

**Comment by PatilHarshh** [comment]
Screenshot (268)
remove this

**Comment by PatilHarshh** [comment]
make more UI more appealing ! it seems like existing one was good

**Comment by Varsani2520** [comment]
ok

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,check it

**Comment by Varsani2520** [comment]
simple web is more attractive and easily understood client as well as user

**Comment by Varsani2520** [comment]
Hey @PatilHarshh ,give me response

**Pull request merged**
